spring:
  main:
    allow-bean-definition-overriding: true

  flyway:
    enabled: false

  # Configuración JWT
  security:
    jwt:
      secret: "mi-clave-secreta-jwt-muy-larga-y-segura-para-desarrollo-123456"
      expiration: 86400000

  # Configuración de base de datos
  datasource:
    url: jdbc:postgresql://localhost:5432/coopcredit_db
    username: postgres
    password: Qwe.123*
    driver-class-name: org.postgresql.Driver

  # Configuración JPA/Hibernate
  jpa:
    hibernate:
      ddl-auto: create  # Para desarrollo
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# Configuración del servidor
server:
  port: 8080
  servlet:
    context-path: /api

# Configuración de Feign Client
risk-central:
  service:
    url: http://localhost:8081  # URL del servicio Risk Central (ajustar según tu entorno)

# Configuración de logging
logging:
  level:
    com.coopcredit.creditapplicationservice: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.springframework.cloud.openfeign: DEBUG